name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-model-deploy:latest

    - name: Deploy to Server (Optional)
      run: |
        # Aqui você pode adicionar comandos para rodar seu container em um servidor de produção
        # ou configurar um serviço como AWS, GCP, ou Azure para rodar o container
        echo "Deployment steps can be added here"

    - name: Logout from DockerHub
      run: docker logout
